#!/usr/bin/env python3
"""Generate datui's built-in FIX dictionary from QuickFIX's data dictionaries.

Reads FIX42.xml, FIX44.xml, FIXT11.xml and FIX50SP2.xml from QuickFIX's `spec/`
directory (fetched from GitHub unless --spec names a local copy) and writes
`crates/datui-lib/src/fix/dictionary.tsv`, one tag a line:

    tag <TAB> name <TAB> type <TAB> data tag <TAB> code=Name;code=Name

Later versions win: a tag's name, type and enum names are FIX 5.0 SP2's where it
has them, then FIX 4.4's, then FIX 4.2's, and the enums of all three are merged.
MsgType (35) takes its names from the message definitions (`D` is
NewOrderSingle). Enum descriptions are QuickFIX's UPPER_SNAKE words, written in
CamelCase (`SELL_SHORT` is SellShort). The data tag is given for a LENGTH field
that sizes a DATA field (95 RawDataLength sizes 96 RawData).

QuickFIX is distributed under the QuickFIX Software License 1.0, whose notice the
generated file carries.

Usage:
    scripts/code/fix_dictionary.py
    scripts/code/fix_dictionary.py --spec ~/src/quickfix/spec
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "crates/datui-lib/src/fix/dictionary.tsv"
BASE = "https://raw.githubusercontent.com/quickfix/quickfix/master/spec/"
FILES = ["FIX42.xml", "FIX44.xml", "FIXT11.xml", "FIX50SP2.xml"]

NOTICE = """\
# datui's built-in FIX dictionary, generated by scripts/code/fix_dictionary.py
# from QuickFIX's FIX42.xml, FIX44.xml, FIXT11.xml and FIX50SP2.xml. Do not edit.
#
# tag, name, type, the DATA tag a LENGTH tag sizes, and enum code=Name pairs.
#
# This product includes software developed by quickfixengine.org
# (http://www.quickfixengine.org/).
#
# The QuickFIX Software License, Version 1.0
# Copyright (c) 2001-2020 Oren Miller
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. The end-user documentation included with the redistribution, if any, must
#    include the following acknowledgment: "This product includes software
#    developed by quickfixengine.org (http://www.quickfixengine.org/)."
#    Alternately, this acknowledgment may appear in the software itself, if and
#    wherever such third-party acknowledgments normally appear.
# 4. The names "QuickFIX" and "quickfixengine.org" must not be used to endorse or
#    promote products derived from this software without prior written
#    permission. For written permission, please contact ask@quickfixengine.org
# 5. Products derived from this software may not be called "QuickFIX", nor may
#    "QuickFIX" appear in their name, without prior written permission of
#    quickfixengine.org
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# QUICKFIXENGINE.ORG OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


def camel(words: str) -> str:
    """`SELL_SHORT` as SellShort; a description already in mixed case is kept."""
    if any(c.islower() for c in words):
        return "".join(part[:1].upper() + part[1:] for part in words.split("_"))
    return "".join(part.capitalize() for part in words.split("_") if part)


def read(text: bytes) -> tuple[dict[int, dict], dict[str, str]]:
    root = ET.fromstring(text)
    fields: dict[int, dict] = {}
    for f in root.iterfind("./fields/field"):
        enums = {}
        for v in f.iterfind("value"):
            enums[v.get("enum")] = camel(v.get("description", ""))
        fields[int(f.get("number"))] = {
            "name": f.get("name"),
            "type": f.get("type"),
            "enums": enums,
        }
    messages = {m.get("msgtype"): m.get("name") for m in root.iterfind("./messages/message")}
    return fields, messages


def fetch(name: str, spec: Path | None) -> bytes:
    if spec is not None:
        return (spec / name).read_bytes()
    with urllib.request.urlopen(BASE + name, timeout=60) as response:
        return response.read()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--spec", type=Path, help="QuickFIX's spec/ directory")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    merged: dict[int, dict] = {}
    messages: dict[str, str] = {}
    for name in FILES:
        fields, msgs = read(fetch(name, args.spec))
        for tag, field in fields.items():
            have = merged.setdefault(tag, {"enums": {}})
            have["name"] = field["name"]
            have["type"] = field["type"]
            have["enums"].update(field["enums"])
        messages.update(msgs)
    if 35 in merged:
        merged[35]["enums"].update(messages)

    by_name = {f["name"]: tag for tag, f in merged.items()}
    lines = [NOTICE.rstrip("\n")]
    for tag in sorted(merged):
        f = merged[tag]
        data = ""
        if f["type"] == "LENGTH":
            for suffix in ("Length", "Len"):
                if f["name"].endswith(suffix):
                    other = by_name.get(f["name"][: -len(suffix)])
                    if other is not None and merged[other]["type"] in ("DATA", "XMLDATA"):
                        data = str(other)
        enums = ";".join(
            f"{code}={name}"
            for code, name in f["enums"].items()
            if code and name and not any(c in code + name for c in "=;\t\n")
        )
        lines.append(f"{tag}\t{f['name']}\t{f['type']}\t{data}\t{enums}".rstrip("\t"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"{len(merged)} tags written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
