#!/usr/bin/env python3
"""
Build an isolated workspace, cache and config for the home-screen demos.

The home screen shows the machine it runs on, so the demos get their own:
a copy of demo/data, seeded recents, and a config that ignores desktop recents.

    python scripts/demos/make-home-fixture.py [--root /tmp/datui-demo]
"""

import argparse
import json
import shutil
from pathlib import Path

DEMO_DATA = Path(__file__).resolve().parents[2] / "demo" / "data"


def build_workspace(workspace: Path) -> None:
    if not (DEMO_DATA / "quant-research").is_dir():
        raise SystemExit(
            f"{DEMO_DATA} is missing the demo datasets. Run demo/build.py "
            "(with --private for the snapshots) before recording."
        )
    shutil.copytree(DEMO_DATA, workspace)
    # A non-data file, which the home screen should not list.
    (workspace / "quant-research" / "README.md").write_text(
        "# quant-research\n\nA trimmed extract for the datui demos.\n"
    )


def seed_cache(cache: Path, workspace: Path) -> None:
    cache.mkdir(parents=True, exist_ok=True)
    recents = [
        workspace / "quant-research/returns",
        workspace / "quant-research/factor_ic",
        workspace / "earthquakes_m6.parquet",
        workspace / "quant-research/risk_factor_cov.parquet",
        workspace / "bitcoin_daily.parquet",
    ]
    (cache / "recents_history.txt").write_text(
        "\n".join(str(p) for p in recents) + "\n"
    )


def write_config(config_home: Path, workspace: Path) -> None:
    out = config_home / "datui"
    out.mkdir(parents=True, exist_ok=True)
    (out / "config.toml").write_text(
        "\n".join(
            [
                "# Generated by scripts/demos/make-home-fixture.py -- do not edit.",
                "[data]",
                f'directories = ["{workspace}"]',
                "use_desktop_recents = false",
                "",
            ]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="/tmp/datui-demo", type=Path)
    args = parser.parse_args()

    root: Path = args.root
    if root.exists():
        shutil.rmtree(root)
    workspace = root / "data"

    build_workspace(workspace)
    seed_cache(root / "cache", workspace)
    write_config(root / "config", workspace)
    # Empty HOME, so no cloud credentials are found.
    (root / "home").mkdir(parents=True, exist_ok=True)

    manifest = {
        "workspace": str(workspace),
        "DATUI_CACHE_DIR": str(root / "cache"),
        "XDG_CONFIG_HOME": str(root / "config"),
        "HOME": str(root / "home"),
    }
    (root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
