#!/usr/bin/env python3
"""
Build the workspace the home-screen demo records against.

The home screen shows whatever is around you -- recents, the working directory,
configured directories -- so a demo of it is a demo of somebody's actual machine.
That is both a privacy problem and a reproducibility one: a tape recorded against a
real research mount cannot be regenerated by anyone else, and may show file names
nobody meant to publish.

So the demo gets its own everything: its own cache directory (so RECENT is seeded
rather than inherited), its own config (with the desktop's recently-used list turned
off, since that is the one source that can surface a file from outside the project),
and its own workspace: a copy of demo/data.

    python scripts/demos/make-home-fixture.py [--root /tmp/datui-demo]
"""

import argparse
import json
import shutil
from pathlib import Path


# The workspace is a copy of demo/data: the public datasets built by demo/build.py
# plus the private snapshots. The home screen's whole point is what it can tell you
# about data before you open it, and that needs data with a shape -- so the demo
# records against the same files the other tapes use.
DEMO_DATA = Path(__file__).resolve().parents[2] / "demo" / "data"


def build_workspace(workspace: Path) -> None:
    if not (DEMO_DATA / "quant-research").is_dir():
        raise SystemExit(
            f"{DEMO_DATA} is missing the demo datasets. Run demo/build.py "
            "(with --private for the snapshots) before recording."
        )
    shutil.copytree(DEMO_DATA, workspace)
    # A stray non-data file, because a real directory has them and the home screen
    # should visibly not offer it.
    (workspace / "quant-research" / "README.md").write_text(
        "# quant-research\n\nA trimmed extract for the datui demos.\n"
    )


def seed_cache(cache: Path, workspace: Path) -> None:
    """Seed RECENT so the demo opens onto a screen that looks used, not empty."""
    cache.mkdir(parents=True, exist_ok=True)
    recents = [
        workspace / "quant-research/prices",
        workspace / "quant-research/factor_ic",
        workspace / "earthquakes_m6.parquet",
        workspace / "quant-research/returns",
        workspace / "bitcoin_daily.parquet",
    ]
    (cache / "recents_history.txt").write_text(
        "\n".join(str(p) for p in recents) + "\n"
    )


def write_config(config_home: Path, workspace: Path) -> None:
    """A config that cannot reach outside the demo.

    `use_desktop_recents = false` is the important line: freedesktop's recently-used
    list is the one input that can put a file from anywhere on the machine on screen,
    and a recording is exactly when that must not happen.
    """
    out = config_home / "datui"
    out.mkdir(parents=True, exist_ok=True)
    (out / "config.toml").write_text(
        "\n".join(
            [
                "# Generated by scripts/demos/make-home-fixture.py -- do not edit.",
                "[data]",
                f'directories = ["{workspace}"]',
                "use_desktop_recents = false",
                "",
            ]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="/tmp/datui-demo", type=Path)
    args = parser.parse_args()

    root: Path = args.root
    if root.exists():
        shutil.rmtree(root)
    workspace = root / "data"

    build_workspace(workspace)
    seed_cache(root / "cache", workspace)
    write_config(root / "config", workspace)
    # An empty HOME. The home screen lists the buckets the machine's cloud
    # credentials reach, and it finds those under ~/.aws and ~/.config/gcloud; the
    # tape points HOME here so the recording shows no bucket of the recorder's.
    (root / "home").mkdir(parents=True, exist_ok=True)

    manifest = {
        "workspace": str(workspace),
        "DATUI_CACHE_DIR": str(root / "cache"),
        "XDG_CONFIG_HOME": str(root / "config"),
        "HOME": str(root / "home"),
    }
    (root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
