name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
       platform:
        - name: linux
          os: ubuntu-latest
          bin: datui
          target: x86_64-unknown-linux-gnu
        - name: windows
          os: windows-latest
          bin: datui.exe
          target: x86_64-pc-windows-msvc

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}

      # Build the binary
      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      # Upload the binary as an artifact
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: datui-${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Download artifacts from the build job
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: datui-linux
          path: ./binaries/linux
      - name: Download binaries (Windows)
        uses: actions/download-artifact@v4
        with:
          name: datui-windows
          path: ./binaries/windows

      # Create a release and upload binaries
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./binaries/linux/datui
            ./binaries/windows/datui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
